### PR TITLE
Do not enforce representability for hybrid binaries in elf imgact.

### LINKED ISSUE #1700: Can not run clang on cheribsd-riscv64-purecap
I have installed llvm-riscv64-hybrid-for-purecap-rootfs by cheribuild.py, but when I run clang on cheribsd-riscv64-purecap, it failed.
the command is:
```
/opt/riscv64-hybrid/llvm-project/bin/clang-14
```
the error message is:
```
Warning: Attempted to load position-dependent executable with non-representable base: /opt/riscv64-hybrid/llvm-project/bin/clang-14
Abort trap
```
Where is the problem? 
Do I need to add specific compilation options when compiling cheribsd-riscv64-purecap？

### PR DESCRIPTION
**Pull request by qwattash**
When loading hybrid position-dependent binaries, we do not care about the representability of the ELF sections. The reservation creation will skip the representability alignment enforcement as well, so avoid complaining about alignment when creating the imgact_capability.

This should fix #1700.

### CODE REVIEW

**Review by bsdjhb — APPROVED** [review]

**Comment by jrtc27** [comment]
Use the __ELF_CHERI or whatever ifdef? We compile imgact_elf once for each ELF type.

**Comment by qwattash** [comment]
> Use the __ELF_CHERI or whatever ifdef? We compile imgact_elf once for each ELF type.

Done

File: sys/kern/imgact_elf.c [hunk 1]
```diff
@@ -597,11 +597,13 @@ __elfN(build_imgact_capability)(struct image_params *imgp,
 		end = MAX(end, seg_addr + seg_size);
 	}
 
+#ifdef __ELF_CHERI
 	if (hdr->e_type == ET_EXEC && !is_aligned(start + rbase,
-	    CHERI_REPRESENTABLE_ALIGNMENT(end - start))) {
+		CHERI_REPRESENTABLE_ALIGNMENT(end - start))) {
```
Comment (arichardson) [inline sys/kern/imgact_elf.c:602]:
```suggestion
	    CHERI_REPRESENTABLE_ALIGNMENT(end - start))) {
```

File: sys/kern/imgact_elf.c [hunk 2]
```diff
@@ -597,11 +597,13 @@ __elfN(build_imgact_capability)(struct image_params *imgp,
...
 		/*
-		 * We can't change the load address for position dependent
-		 *  executables, so we have to give up and report an error.
+		 * We can't change the load address for position
+		 * dependent executables, so we have to give up and
+		 * report an error.
```
Comment (jrtc27) [inline sys/kern/imgact_elf.c:606]: If you want to reformat the existing code (even if just comments), please do that separately from adding the ifdef?

File: sys/kern/imgact_elf.c [hunk 3]
```diff
@@ -610,13 +612,16 @@ __elfN(build_imgact_capability)(struct image_params *imgp,
...
-	 * Note: vm_map_reservation_create aligns down, but we have to align
-	 * upwards here to avoid rounding down to zero for the main executable.
-	 * For RTLD we also align upwards to avoid aligning down into the
-	 * memory region for the main binary.
+	 * Note: vm_map_reservation_create aligns down, but we have to
+	 * align upwards here to avoid rounding down to zero for the main
+	 * executable. For RTLD we also align upwards to avoid aligning
+	 * down into the memory region for the main binary.
 	 */
 	reservation = roundup2(start + rbase,
```
Comment (jrtc27) [inline sys/kern/imgact_elf.c:620]: If you do `reservation = start + rbase` before the ifdef and do `reservation = roundup2(reservation, ...)` here then you can shave off needing an #else

File: sys/kern/imgact_elf.c [hunk 4]
```diff
@@ -597,11 +597,13 @@ __elfN(build_imgact_capability)(struct image_params *imgp,
 		end = MAX(end, seg_addr + seg_size);
 	}
 
+#ifdef __ELF_CHERI
 	if (hdr->e_type == ET_EXEC && !is_aligned(start + rbase,
```
Comment (jrtc27) [inline sys/kern/imgact_elf.c:601]: And I guess use reservation here too

**Review by jrtc27 — APPROVED** [review]

**Comment by bsdjhb** [comment]
One nit: s/commont/comment/ in the second log message.

**Review by bsdjhb — APPROVED** [review]
