### PR TITLE
c18n: Fix rtld_bind reentry bug

### LINKED ISSUE #2130: Invalid permissions for mapped object in pkg64cb with globally enabled c18n
On dev (https://github.com/CTSRD-CHERI/cheribsd/commit/bdeff30fb6b1744816f43ed8a3c2f0a133d872c1) running GENERIC-MORELLO-PURECAP, `pkg64cb` crashes when executed for the first time with `security.cheri.lib_based_c18n_default` set to `1`:
```
root@cheribsd:~ # sysctl security.cheri.lib_based_c18n_default=1
security.cheri.lib_based_c18n_default: 0 -> 1
root@cheribsd:~ # gdb pkg64cb
(...)
Reading symbols from pkg64cb...
Reading symbols from /usr/lib/debug//usr/sbin/pkg64cb.debug...
(gdb) r
Starting program: /usr/sbin/pkg64cb 
The package management tool is not yet installed on your system.
Do you want to fetch and install it now? [y/N]: y
Bootstrapping pkg from http://pkg.CheriBSD.org/CheriBSD:20240617:aarch64cb, please wait...
Program received signal SIGSEGV, Segmentation fault.
Invalid permissions for mapped object.
0x0000fffffff7fe20 in ?? ()
(gdb) bt
#0  0x0000fffffff7fe20 in ?? ()
#1  0x0000fffffff7fe20 in ?? ()
Backtrace stopped: frame did not save the PC
(gdb) 
```
The crash doesn't occur if I change `security.cheri.lib_based_c18n_default` to `0`, run `pkg64cb`, change `security.cheri.lib_based_c18n_default` to `1` and run `pkg64cb` again. There must be some code path in the pkg bootstrapping process that triggers this crash.

### PR DESCRIPTION
**Pull request by dpgao**
~Just for CI. Do not merge yet.~

This should fix #2130.

### CODE REVIEW

File: libexec/rtld-elf/rtld_c18n.c [hunk 1]
```diff
@@ -745,14 +745,23 @@ init_stk_table(struct stk_table *table, struct tcb_wrapper *wrap)
...
+	 * RTLD's actual stack is the Executive stack which does not need to be
+	 * stored in the stack lookup table. Instead, fill the table entry with
+	 * a one-byte dummy stack.
+	 *
+	 * Note that NULL cannot be used here because a compartment can then
+	 * pretend to be RTLD when a signal is delivered. Nor can a zero-length
+	 * stack be used because the signal handler uses the recorded size of
+	 * the stack to determine whether it has been allocated.
+	 */
+	static char dummy_stk;
```
Comment (jrtc27) [inline libexec/rtld-elf/rtld_c18n.c:763]: This is ugly, surely there's a better way. Where does this end up being used to determine that the compartment is RTLD, anyway? Isn't the trusted stack tracking the compartment ID?

File: libexec/rtld-elf/rtld_c18n.h [hunk 2]
```diff
@@ -118,9 +118,34 @@ struct stk_table {
...
+		.callee = cid_to_index(RTLD_COMPART_ID)
+	};
+	set_trusted_stk(tf);
+	return (tf);
+}
+
+static inline struct trusted_frame *
+pop_dummy_rtld_trusted_frame(struct trusted_frame *tf)
+{
+	assert(get_trusted_stk() == tf);
```
Comment (jrtc27) [inline libexec/rtld-elf/rtld_c18n.h:144]: So why not just make it implicit?...

File: libexec/rtld-elf/rtld_c18n.h [hunk 3]
```diff
@@ -118,9 +118,34 @@ struct stk_table {
...
 struct tcb *c18n_allocate_tcb(struct tcb *);
 void c18n_free_tcb(void);
 
+/*
+ * When entering the RTLD without a trampoline (e.g., during lazy binding, TLS
+ * lookup, or stack resolution), a dummy trusted frame indicating that the
+ * current compartment is RTLD must be pushed.
+ */
+static inline struct trusted_frame *
+push_dummy_rtld_trusted_frame(struct trusted_frame *tf)
```
Comment (jrtc27) [inline libexec/rtld-elf/rtld_c18n.h:132]: The only case when this isn't get_trusted_stk() is when you first create the stack. Implicitly use get_trusted_stk(), and then upon creation you just need to set_trusted_stk() before calling this.

**Comment by jrtc27** [comment]
Please also add a regression test to cheribsdtest_ifunc.c

File: libexec/rtld-elf/rtld_c18n.c (hunk 1 above)
Comment (dpgao) [reply libexec/rtld-elf/rtld_c18n.c:763]: > Isn't the trusted stack tracking the compartment ID?

This is generally true except at certain points in the trampoline where the trusted stack becomes temporarily out-of-sync with the currently installed untrusted stack.

The signal handler needs to handle such situations and makes a few guesses about the actual compartment that the current untrusted stack belongs to. It does so by checking whether the current untrusted stack is a subset of one of the candidate compartments' stack. Hence the dummy stack must be tagged and have positive length to prevent compartments from impersonating as RTLD.

File: libexec/rtld-elf/rtld_c18n.h (hunk 2 above)
Comment (dpgao) [reply libexec/rtld-elf/rtld_c18n.h:144]: I want to retain the assertion because it would be very hard to debug if something goes wrong here.

Comment (jrtc27) [reply libexec/rtld-elf/rtld_c18n.h:144]: What does asserting that the input is the one valid value achieve? The function can just use get_trusted_stk() itself, it doesn't need an argument.

File: libexec/rtld-elf/rtld_c18n.c (hunk 1 above)
Comment (jrtc27) [reply libexec/rtld-elf/rtld_c18n.c:763]: "makes a few guesses about the actual compartment that the current untrusted stack belongs to" doesn't fill me with confidence as to the security of this mechanism

File: libexec/rtld-elf/rtld_c18n.h (hunk 2 above)
Comment (dpgao) [reply libexec/rtld-elf/rtld_c18n.h:144]: My main worry is that somebody pushed to the trusted stack and forgot to pop. The assertion helps to catch that.

Comment (jrtc27) [reply libexec/rtld-elf/rtld_c18n.h:144]: And how does this code help catch that?

Comment (dpgao) [reply libexec/rtld-elf/rtld_c18n.h:144]: As in, this assertion checks that nobodies made unbalanced push/pops to the trusted stack between the pair of push and pop that I am doing right now.

File: libexec/rtld-elf/rtld_c18n.c (hunk 1 above)
Comment (dpgao) [reply libexec/rtld-elf/rtld_c18n.c:763]: The security argument definitely has lots of room for improvement. But at least signal handling should be functionally correct now.

**Comment by dpgao** [comment]
@jrtc27 I've added a regression test. Regarding the use of implicit arguments, I'm still in favour of explicit arguments because then we are able to track canonical state of the trusted stack instead of relying on a special register, which might be corrupted between a push and a pop.
