### PR TITLE
Fix crossbuild bootstrap after MK_SYMVER removal

### LINKED ISSUE #463: foreign cross build depends on removed MK_SYMVER
@bsdjhb removed MK_SYMVER upstream and tools/build/cross-build/libfreebsd/Makefile.inc depends on it.  I've reverted the change in an upcoming merge and in the freebsd-crossbuild branch, but we need to work out what we should replace it with.

### PR DESCRIPTION
**Pull request by arichardson**
Fixes #463

### CODE REVIEW

File: tools/build/cross-build/include/common/sys/cdefs.h [hunk 1]
```diff
@@ -116,15 +116,33 @@
...
+#ifndef __sym_default
+#define	__sym_default(sym,impl,verid)	\
+	__asm__(".symver " #impl ", " #sym "@@@" #verid)
+#endif
+#ifndef __warn_references
+#define	__warn_references(sym,msg)	\
+	__asm__(".section .gnu.warning." #sym);	\
+	__asm__(".asciz \"" msg "\"");	\
+	__asm__(".previous")
+#endif
```
Comment (brooksdavis) [inline tools/build/cross-build/include/common/sys/cdefs.h:138]: Do we actually need valid definitions of these?

Comment (arichardson) [reply tools/build/cross-build/include/common/sys/cdefs.h:138]: Probably not, I guess I could define them as empty for both ELF and MACHO

File: tools/build/cross-build/include/common/sys/cdefs.h [hunk 2]
```diff
@@ -116,15 +116,33 @@
...
 #else
 #define __weak_reference(sym,alias)	\
     static int alias() __attribute__ ((weakref (#sym)));
```
Comment (jrtc27) [inline tools/build/cross-build/include/common/sys/cdefs.h:141]: Would this not be better as `#pragma weak alias = sym`? I don't think your current solution even actually provides the semantics wanted by `__weak_reference`, namely to export the symbol (`weakref` requires it to be static) as weak. The pragma is old and supported by both GCC and Clang. Quite frankly FreeBSD should move to this for its own cdefs.h anyway :) it produces basically-identical code on Clang for ELF (.weak/.set rather than .weak/.equ), and  has the advantage that it also emits the correct .weak_reference for Mach-O.

Comment (jrtc27) [reply tools/build/cross-build/include/common/sys/cdefs.h:141]: *sigh*, right, #pragma doesn't work in the body of #define... :(

Comment (arichardson) [reply tools/build/cross-build/include/common/sys/cdefs.h:141]: I just copied this from the main freebsd cdefs.h. but I guess I can just keep it empty since we don't really need it to work properly.

Comment (arichardson) [reply tools/build/cross-build/include/common/sys/cdefs.h:141]: There's also _Pragma that should work in macros

Comment (jrtc27) [reply tools/build/cross-build/include/common/sys/cdefs.h:141]: Ah, yes, good, we should be able to rely on C99 and C++11 these days. You want:

```c
#define __do_pragma(x) _Pragma(#x)
#define __weak_reference(sym, alias) __do_pragma(weak alias = sym)
```
You can't just do `#define __weak_reference(sym, alias) _Pragma("weak "#alias" = "#sym)` as one would naively expect because `_Pragma` wants a single string literal and adjacent ones aren't implicitly concatenated.
